export const SET_WALLET_META = "SET_WALLET_META";
export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const SET_CURRENT_ACCOUNT_INDEX = "SET_CURRENT_ACCOUNT_INDEX";
export const SET_MNEMONIC = "SET_MNEMONIC";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_CONTACTS = "SET_CONTACTS";
export const GET_ACCOUNT_DETAILS = "GET_ACCOUNT_DETAILS";
export const GET_ACCOUNT_DETAILS_LOADING = "GET_ACCOUNT_DETAILS_LOADING";
export const CLEAR_STATES = "CLEAR_STATES";
export const GET_All_TRANSACTIONS = "GET_All_TRANSACTIONS";
export const GET_All_TRANSACTIONS_LOADING = "GET_LATEST_TRANSACTIONS_LOADING";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_SELECTED_COIN = "SET_SELECTED_COIN";
export const SET_SELECTED_COIN_LOADING = "SET_SELECTED_COIN_LOADING";

export const GET_PSIX_MARKET_PRICE = "GET_PSIX_MARKET_PRICE";
export const CREATE_TX_LOADING = "CREATE_TX_LOADING";

export const SET_SELECTED_ROW = "SET_SELECTED_ROW";

export const SET_GRAPH_DATA = "SET_GRAPH_DATA";
export const SET_GRAPH_DATA_LOADING = "SET_GRAPH_DATA_LOADING";

export const GET_MARKET_PRICE = "GET_MARKET_PRICE";
export const SEND_TXS_LOADING = "SEND_TXS_LOADING";
export const CLOSE_SEND_TXS_BAR = "CLOSE_SEND_TXS_BAR";

export const SUCCESS_BAR_CONTENT = "SUCCESS_BAR_CONTENT";
export const ERROR_BAR_CONTENT = "ERROR_BAR_CONTENT";

export const SENT_TXS_HASH = "SENT_TXS_HASH";
export const ACTIVE_ACCOUNTS = "ACTIVE_ACCOUNTS";
export const ACTIVE_INDEX = "ACTIVE_INDEX";

export const BACKUP_FILE_SUCCESS_BAR_CONTENT = "BACKUP_FILE_SUCCESS_BAR_CONTENT";
