import { palette } from "./pellete";

export const typography = {
    h1: {
        color: palette.primary.lightBlack,
        fontWeight: 500,
        fontSize: 18,
        margin: "0 0 19.6px 0",
        fontFamily: "Gilroy-Regular",
        textAlign: "center",
        borderBottom: "1px solid black",
        whiteSpace: "nowrap",
    },
    h2: {
        fontFamily: "Gilroy-SemiBold",
        fontSize: 15,
        fontWeight: 600,
        lineHeight: 1.5,
        color: "#464646",
        margin: "4px 0px 4px 0px",
    },
    h3: {
        color: "#23224e",
        fontFamily: "Gilroy-Regular",
        fontWeight: "normal",
        fontSize: "14px",
        margin: "15px 0 20px 0",
        textAlign: "center",
        maxWidth: "350px",
    },
    h4: {
        color: palette.primary.darkWhite,
        fontWeight: 300,
        fontSize: "14px",
        letterSpacing: "normal",
        fontFamily: "Gilroy-Light",
        lineHeight: 1.5,
        margin: "0 0 0 12px",
    },
    h5: {
        color: palette.text.primary,
        fontWeight: "300",
        fontFamily: "Gilroy-Regular",
        fontSize: "16px",
        letterSpacing: "normal",
        fontStyle: "normal",
        textAlign: "center",
        lineHeight: 1.56,
    },
    h6: {
        color: palette.text.darkWhite,
        fontWeight: "normal",
        fontSize: "15px",
        letterSpacing: "normal",
        lineHeight: 1.21,
        fontFamily: "Gilroy-Regular",
        marginTop: "9px",
        textAlign: "center",
    },
    subtitle1: {
        color: palette.primary.blue,
        fontSize: "18px",
        fontFamily: "Gilroy-Regular",
        letterSpacing: "-0.05px",
        lineHeight: "2",
        fontWeight: "normal",
        margin: "17px 0px 0px 0",
    },
    subtitle2: {
        color: palette.primary.lightBlack,
        display: "flex",
        margin: "20px 0px 1.3px 0px",
        fontFamily: "Gilroy-Regular",
        fontSize: 15,
        fontWeight: 500,
        lineHeight: 1.53,
        textAlign: "left",
    },
    body1: {
        color: palette.primary.blue,
        fontFamily: "Gilroy-Light",
        fontSize: "15px",
        fontWeight: 400,
        lineHeight: 1.53,
        textAlign: "center",
    },
    body2: {
        color: "#23224e",
        margin: "5px 0px 15px 0px",
        fontSize: 16,
        fontFamily: "Gilroy-LightItalic",
        lineHeight: 1.56,
        borderBottom: "1px solid #23224e",
        cursor: "pointer",
    },
    button: {
        color: palette.text.primary,
        fontSize: "14px",
    },
    caption: {
        color: palette.primary.blue,
        fontFamily: "Gilroy-Regular",
        fontSize: 12,
        lineHeight: 1.5,
        textAlign: "left",
        fontWeight: 500,
    },
    overline: {
        color: palette.text.secondary,
        fontSize: "11px",
        fontWeight: 500,
        letterSpacing: "normal",
        textTransform: "captialize",
    },
};
