export const SET_AUTHENTICATION_MNEMONIC_WORDS =
  "SET_AUTHENTICATION_MNEMONIC_WORDS";
export const SESSION_LOGIN = "SESSION_LOGIN";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
export const CLEAR_WORDS = "CLEAR_WORDS";
