export const MuiButton = {
    root: {
        // padding: "18px 60px !important",
        maxWidth: "240px !important",
        minWidth: "240px !important",
        width: "100% !important",
        height: 49,
        borderTopRightRadius: "0px",
        borderTopLeftRadius: "25px",
        borderBottomRightRadius: "25px",
        borderBottomLeftRadius: "25px",
        color: "#fff",
        backgroundColor: "#d5da43 !important",
        fontFamily: "Gilroy-Regular",
        margin: "15px auto",
        fontSize: 18,
        fontWeight: "normal",
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 0.33,
        letterSpacing: 0.36,
        textTransform: "capitalize",
    },
    outlined: {
        // padding: "8px 25px 8px 25px !important",
        borderRadius: "5px",
        color: "#23224e",
        backgroundColor: "#fff !important",
        border: "solid 1px #23224e",
        fontFamily: "Gilroy-Regular",
        margin: "0px 0px 15px 0px",
        fontSize: 18,
        letterSpacing: 0.36,
        textTransform: "capitalize",
        maxWidth: "240px !important",
        minWidth: "240px !important",
        width: "100% !important",
        height: 49,
    },
};
